// export const items = [
//   {
//     item: "Apples",
//   },
//   {
//     item: "Cinnamon Toast Crunch",
//   },
//   {
//     item: "Octopus",
//   },
//   {
//     item: "Three beans",
//   },
//   {
//     item: "big big bean toast",
//   },
//   {
//     item: "cinnamon waffles",
//   },
//   {
//     item: "cinnamon waffles",
//   },
// ];

export const items = {
  "0": "caramel frappuccino",
  "1": "caramel ribbon crunch frappuccino",
  "2": "strawberry acai lemonade",
  "3": "birthday cake pop",
  "4": "pink drink",
  "5": "iced caramel macchiato",
  "6": "white chocolate mocha",
  "7": "pike place roast",
  "8": "caramel macchiato",
  "9": "caffe latte",
  "10": "mocha cookie crumble frappuccino",
  "11": "iced coffee",
  "12": "vanilla bean creme frappuccino",
  "13": "cheese danish",
  "14": "strawberry acai",
  "15": "mango dragonfruit lemonade",
  "16": "iced white chocolate mocha",
  "17": "double-smoked bacon, cheddar & egg sandwich",
  "18": "bacon, gouda & egg sandwich",
  "19": "banana walnut & pecan loaf",
  "20": "mocha frappuccino",
  "21": "butter croissant",
  "22": "vanilla sweet cream cold brew",
  "23": "chocolate croissant",
  "24": "caffe mocha",
  "25": "mango dragonfruit",
  "26": "sausage, cheddar & egg sandwich",
  "27": "chai tea latte",
  "28": "chocolate cake pop",
  "29": "caffe americano",
  "30": "iced lemon loaf",
  "31": "iced caffe latte",
  "32": "iced brown sugar oatmilk shaken espresso",
  "33": "iced chai tea latte",
  "34": "strawberry creme frappuccino",
  "35": "ham & swiss croissant",
  "36": "dragon drink",
  "37": "bacon & gruyere egg bites",
  "38": "pumpkin cream cold brew",
  "39": "java chip frappuccino",
  "40": "pumpkin & pepita loaf",
  "41": "spinach, feta & egg white wrap",
  "42": "honey citrus mint tea",
  "43": "iced black tea",
  "44": "cappuccino",
  "45": "egg white & roasted red pepper egg bites",
  "46": "hot chocolate",
  "47": "starbucks cold brew coffee",
  "48": "turkey bacon, cheddar & egg white sandwich",
  "49": "iced matcha tea latte",
  "50": "iced green tea",
  "51": "pumpkin spice latte",
  "52": "iced toasted vanilla oatmilk shaken espresso",
  "53": "double chocolate brownie",
  "54": "impossible breakfast sandwich",
  "55": "salted caramel cream cold brew",
  "56": "blueberry muffin",
  "57": "cinnamon coffee cake",
  "58": "caramel brulee latte",
  "59": "unicorn cake pop",
  "60": "matcha creme frappuccino",
  "61": "iced caffe americano",
  "62": "chocolate chip cookie",
  "63": "double chocolaty chip creme frappuccino",
  "64": "featured starbucks dark roast coffee",
  "65": "peppermint mocha",
  "66": "crispy grilled cheese on sourdough",
  "67": "tomato & mozzarella on focaccia",
  "68": "almond croissant",
  "69": "iced caffe mocha",
  "70": "paradise drink",
  "71": "plain bagel",
  "72": "iced shaken espresso",
  "73": "iced peach green tea lemonade",
  "74": "starbucks blonde espresso roast",
  "75": "iced chocolate almondmilk shaken espresso",
  "76": "white chocolate mocha frappuccino",
  "77": "blueberry scone",
  "78": "chocolate cookie crumble creme frappuccino",
  "79": "matcha tea latte",
  "80": "ethos bottled water",
  "81": "nitro cold brew",
  "82": "cheese & fruit protein box",
  "83": "flat white",
  "84": "caramel ribbon crunch creme frappuccino",
  "85": "pumpkin cream cheese muffin",
  "86": "iced pumpkin spice latte",
  "87": "cinnamon dolce latte",
  "88": "pumpkin spice frappuccino",
  "89": "iced coffee with milk",
  "90": "coffee frappuccino",
  "91": "iced apple crisp oatmilk macchiato",
  "92": "everything bagel",
  "93": "lemonade",
  "94": "caffe vanilla frappuccino",
  "95": "petite vanilla bean scone",
  "96": "pumpkin scone",
  "97": "owl cake pop",
  "98": "vanilla biscotti with almonds",
  "99": "chai creme frappuccino",
  "100": "string cheese",
  "101": "espresso frappuccino",
  "102": "apple crisp oatmilk macchiato",
  "103": "white hot chocolate",
  "104": "cinnamon raisin bagel",
  "105": "pb&j protein box",
  "106": "marshmallow dream bar",
  "107": "salted almond chocolate bites",
  "108": "caffe misto",
  "109": "avocado spread",
  "110": "mint majesty",
  "111": "blended strawberry lemonade",
  "112": "iced cinnamon dolce latte",
  "113": "caramel apple spice",
  "114": "squirrel brand fruit & nut",
  "115": "starbucks cold brew coffee with milk",
  "116": "white chocolate creme frappuccino",
  "117": "kind salted caramel & dark chocolate nut bar",
  "118": "glazed doughnut",
  "119": "very berry hibiscus",
  "120": "perfect bar - dark chocolate chip peanut butter",
  "121": "sumatra",
  "122": "decaf pike place roast",
  "123": "veranda blend",
  "124": "caffe verona",
  "125": "galvanina sparkling water",
  "126": "iced flat white",
  "127": "spearmint gum",
  "128": "kind blueberry vanilla & cashew bar",
  "129": "hippeas - white cheddar",
  "130": "perfect bar peanut butter",
  "131": "salt & vinegar kettle potato chips",
  "132": "pumpkin spice creme frappuccino",
  "133": "very berry hibiscus lemonade",
  "134": "steamed milk",
  "135": "espresso",
  "136": "vanilla creme",
};
